### ISSUE TITLE
Unresolved reference BR.view

### ISSUE THREAD

**Issue by tenSunFree** [thefuntasty/mvvm-android#110]
Affected Device(s)
Answer︰HTC U11 with Android 9.0。
![2020-01-20_065031](https://user-images.githubusercontent.com/23090085/72689879-32ddae00-3b51-11ea-9228-d37959ae2f45.jpg)

Describe the Bug:
Add a clear description about the problem.
Answer︰打開example和example-minimal中的BaseActivity，會出現Unresolved reference的相關錯誤訊息。
![2020-01-20_064201](https://user-images.githubusercontent.com/23090085/72689771-feb5bd80-3b4f-11ea-8dea-2c3bb425cc5c.jpg)

Expected Behavior:
A clear description of what you expected to happen.
Answer︰同Describe the Bug所述。

請問產生錯誤訊息的原因是什麼？或者有什麼方法可以讓它不要報錯嗎？謝謝。

**Comment by skywall** [comment]
Hi @tenSunFree, can you please describe your issue in English?

What do I see in images, you probably have a problem with unresolved references. These `BR` variables are generated only if you have at least one layout where have you used them for example: 
`res/layout/activity_main.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    tools:context=".ui.main.MainActivity">

    <data>

        <variable
            name="view"
            type="com.thefuntasty.mvvmsample.ui.main.MainView"/>

        <variable
            name="viewModel"
            type="com.thefuntasty.mvvmsample.ui.main.MainViewModel"/>

        <variable
            name="viewState"
            type="com.thefuntasty.mvvmsample.ui.main.MainViewState"/>
    </data>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"/>
</layout>
```

**Comment by tenSunFree** [comment]
Hi @skywall 

I found that the original import is "import com.thefuntasty.mvvm.BR"
![2020-01-20_183043](https://user-images.githubusercontent.com/23090085/72719788-7a952180-3bb3-11ea-9f50-65f731a40fdf.jpg)

But there are two kinds of the same "import com.thefuntasty.mvvm.BR"
Then Android Studio couldn't identify which one to use
![2020-01-20_183741](https://user-images.githubusercontent.com/23090085/72720192-6140a500-3bb4-11ea-9dc8-aa1e0b8fb4ea.jpg)
![2020-01-20_183901](https://user-images.githubusercontent.com/23090085/72720194-6140a500-3bb4-11ea-8018-997e8b27d3b6.jpg)

The current solution is to modify to "import com.thefuntasty.mvvmsample.BR"
![2020-01-20_184429](https://user-images.githubusercontent.com/23090085/72720470-06f41400-3bb5-11ea-950b-ce12afc4ebeb.jpg)

**Comment by skywall** [comment]
@tenSunFree Can you please share a link to repository where it is possible to reproduce the issue?

**Comment by tenSunFree** [comment]
@skywall 

I downloaded the zip directly to open it, and then the issue appeared
![2020-01-20_201601](https://user-images.githubusercontent.com/23090085/72726038-512fc200-3bc2-11ea-911c-6ec6503d3a95.jpg)

Do you want me to push the wrong version that is currently displayed on my computer to github? But is there any difference between this and your current version on github?

**Comment by skywall** [comment]
@tenSunFree I have just tried to download zip, open it in Android Studio, build and everything worked fine, without any changes. 

On the other hand, you're right we should use the reference to BR from a different package.

**Comment by skywall** [comment]
@tenSunFree This should be resolved. Feel free to reopen the issue if you still encounter a problem. Thanks for reporting.
