### ISSUE TITLE
Change interactors initialisation paradigm

### ISSUE THREAD

**Issue by skywall** [thefuntasty/mvvm-android#54]
We are facing multiple issues with current interactors behaviour. 
1. Interactors are not mutable objects. Developers do not intuitively understand it and it leads to confusion. Example:
```
val interactor1 = myInteractor.init("1")
val interactor2 = myInteractor.init("2")

interactor1.execute { }
```

Code above causes interactor run initialized with value `2`. This might tend to unexpected and questionable behavior.

2. There are 2 ways to `run` interactor. Through `execute()` and `executeStream()` method. Second one has nothing to do with interactors => rename to `executeSingle()` etc.

**Comment by SumeraMartin** [comment]
How do you wanna solve the first one? If `init` will return a different object then execute won't stop the execution of the previous interactor which would cause more problems then the current implementation. The current way of how we are using interactors:
```
fun load() {
    myInteractor.init("1").execute { ...  }
}

fun retryClicked() {
    load()
}
```
This wouldn't work if `init` will return a different object.

The possible solution would be the usage of an object which would be used as an argument of the `execute` method:
```
abstract class BaseSingle<RETURN_VALUE, ARGS> {

    protected abstract fun prepare(args: ARGS) : Single<RETURN_VALUE>

    fun execute(args: ARGS, doOnNext: () -> Unit) {
        ...
    }
}

class LoadDataSingler : BaseSingle<String, LoadDataSingler.Args>() {

    data class Args(val id: Int)

    override fun prepare(args: Args): Single<String> {
        return Single.just(args.id).map { "X" }
    }
}

fun load() {
    val interactor = LoadDataSingler()
    
    val args1 = LoadDataSingler.Args(1)
    val args2 = LoadDataSingler.Args(2)
    
    interactor.execute(args1) {
        
    }
}
```
